apiVersion: kro.run/v1alpha1
kind: Webapp
metadata:
  name: demo-app
  namespace: kro-demo
spec:
  name: demo-6b39
  project: gitopscon-na
  region: europe-west1
  model: meta-llama/Llama-3.2-1B-Instruct
